inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

require: rubocop-rspec

AllCops:
  TargetRubyVersion: 3.3.4
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'bin/**'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'config/puma.rb'
    - 'node_modules/**/*'
Layout/LineLength:
  Max: 120
Layout/AccessModifierIndentation:
  Enabled: false
Metrics/AbcSize:
  Max: 20
Metrics/BlockLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Rails/FilePath:
  Enabled: false
Rails/Blank:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/VerifiedDoubles:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GuardClause:
  MinBodyLength: 2
Style/StringLiterals:
  EnforcedStyle: single_quotes
