version: 2.1

orbs:
  ruby: circleci/ruby@1

jobs:
  checking:
    docker:
      - image: cimg/ruby:3.1.2
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rubocop-check:
          format: progress
          label: Inspecting with Rubocop
  test:
    docker:
      - image: cimg/ruby:3.1.2
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rspec-test

workflows:
  version: 2
  build_and_test:
    jobs:
      - checking
      - test
