name: "Lint and Test"
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.0
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.4.2
        bundler-cache: true
    - run: bundle exec rubocop

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.0
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.4.2
        bundler-cache: true
    - run: bundle exec rspec
